layer: conceptual
entity: ProductCategory
description: "Hierarchical classification system for organizing products. Categories can have parent categories creating a multi-level taxonomy for seeds, plants, tools, and accessories."

attributes:
  - name: productcategory_bk
    description: "Unique identifier for the product category (business key)"
    type: string
    example: "CAT-001"
    
  - name: productcategory_parent_bk
    description: "Parent category business key for hierarchical structure"
    type: string
    example: "CAT-000"
    
  - name: Name
    description: "Category name"
    type: string
    example: "Gemüsesamen"

relationships:
  - name: is_grouped_into
    target: ProductCategory
    type: M:1
    description: "Category is grouped into parent category (self-referential hierarchy)"

normalization_hints:
  multi_valued: []
  redundant: []
  constrained: []