layer: conceptual
entity: Product
description: "Item available for purchase in the Willibald catalog including seeds, plants, tools, and gardening supplies. Each product has pricing, planting information, and belongs to a product category."

attributes:
  - name: product_bk
    description: "Unique identifier for the product (business key)"
    type: string
    example: "P5001"
    
  - name: Bezeichnung
    description: "Product name or description"
    type: string
    example: "Tomate Roma Bio-Saatgut"
    
  - name: Pflanzabstand
    description: "Recommended planting distance in centimeters"
    type: number
    example: "50"
    
  - name: Pflanzort
    description: "Recommended planting location (sun, shade, greenhouse)"
    type: string
    example: "Sonnig"
    
  - name: Preis
    description: "Current retail price of the product"
    type: decimal
    example: "4.99"
    
  - name: productcategory_bk
    description: "Foreign key reference to product category"
    type: string
    example: "CAT-001"
    
  - name: Typ
    description: "Product type classification"
    type: string
    example: "Saatgut"
    
  - name: Umfang
    description: "Package size or quantity"
    type: string
    example: "50 Korn"

relationships:
  - name: is_assigned_to
    target: ProductCategory
    type: M:1
    description: "Product is assigned to a product category"

normalization_hints:
  multi_valued: []
  redundant: []
  constrained: 
    - Preis